### ISSUE TITLE
Unable to install stream because of pycrypto on ubuntu 14.04

### ISSUE THREAD

**Issue by BHushanRathod** [GetStream/stream-django#70]
I'm trying to install stream on my ubuntu 14.04 system using `pip install stream_django` on django framework. but it returns me an error on pycrypto package dependency. It there any alternative I can use to install stream_django package.?

Here are details of my development system.
-Computer-
----------------
Processor		: 2x Intel(R) Core(TM)2 Duo CPU     T6400  @ 2.00GHz
Memory		        : 3040MB (2455MB used)
Operating System	: Ubuntu 14.04.5 LTS

-Operating System-
----------------
-Version-
Kernel		: Linux 4.4.0-97-generic (x86_64)
Compiled		: #120~14.04.1-Ubuntu SMP Wed Sep 20 15:53:13 UTC 2017
C Library		: Unknown
Default C Compiler		: Unknown
Distribution		: Ubuntu 14.04.5 LTS

-Development Environment Setup-
----------------
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Django==1.11.4
djangorestframework==3.6.3

Here is my pip install output file.
------------------------------------------
[stream_pip_output.txt](https://github.com/GetStream/stream-django/files/1513641/stream_pip_output.txt)

**Comment by tbarbugli** [comment]
Educated guess based on error log is that you miss build dep or some headers

Can you try this before installing the client?

apt-get install build-dep python-dev

On Nov 29, 2017 12:43 PM, "BHushan Rathod" <notifications@github.com> wrote:

I'm trying to install stream on my ubuntu 14.04 system using pip install
stream_django on django framework. but it returns me an error on pycrypto
package dependency. It there any alternative I can use to install
stream_django package.?
Here are details of my development system.
-Computer-

Processor : 2x Intel(R) Core(TM)2 Duo CPU T6400 @ 2.00GHz
Memory : 3040MB (2455MB used)
Operating System : Ubuntu 14.04.5 LTS
-Operating System-

-Version-
Kernel : Linux 4.4.0-97-generic (x86_64)
Compiled : #120~14.04.1-Ubuntu SMP Wed Sep 20 15:53:13 UTC 2017
C Library : Unknown
Default C Compiler : Unknown
Distribution : Ubuntu 14.04.5 LTS
-Development Environment Setup-

Python 3.4.3 (default, Nov 17 2016, 01:08:31)
[GCC 4.8.4] on linux
Django==1.11.4
djangorestframework==3.6.3
Here is my pip install output file.

stream_pip_output.txt
<https://github.com/GetStream/stream-django/files/1513641/stream_pip_output.txt>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GetStream/stream-django/issues/70>, or mute the thread

**Comment by BHushanRathod** [comment]
Thanks for the reply. I did try both `apt-get build-dep python-dev` and `apt-get build-dep python3-dev` which installed some base packages. Then again i tried `pip install stream_django` which again returned me the same `RuntimeError: autoconf error` error.

**Comment by tbarbugli** [comment]
the actual error is stored in a separate log file (config.log) can you attach that as well?

another common issue is missing ssl headers

```
apt-get install libssl-dev
```

**Comment by dwightgunning** [comment]
Closing as the issue opener is out of contact.

Likely this is resolved with 02ea36c1824afac1d9a5667c6948c7c6598bc7b8 and the release of stream-django 1.4.0.

Available from [PyPI](https://pypi.python.org/pypi/stream-django/1.4.0).

If it's still an issue let us know, provide the `config.log` and we can re-open the issue.
