### ISSUE TITLE
Where is the dynamic frontend?

### ISSUE THREAD

**Issue by devxpy** [GetStream/stream-django#82]
At first I thoght the frontend would dynamically update, but it doesn't!

Why not include the JS with the template tag you guys have?

**Comment by pterk** [comment]
In part because it involves picking a javascript framework. Having said that maybe you'll be interested in  the react components that are being developed (Note the beta disclaimer): https://github.com/GetStream/react-activity-feed or check out some of the demo apps (winds / cabin) that have some fancy dynamics (although admittedly not with a django backend). Links 
to the tutorials and github repo's can be found on the blog: https://getstream.io/blog/

**Comment by devxpy** [comment]
Well you could just use SSE.
